// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestForCompanies.Models;

namespace TestForCompanies.Migrations
{
    [DbContext(typeof(TestForCompaniesContext))]
    [Migration("20200604191520_OtherEntity")]
    partial class OtherEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestForCompanies.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cnpj");

                    b.Property<string>("TradingName");

                    b.Property<string>("Uf");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("TestForCompanies.Models.Purveyor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Cnpj");

                    b.Property<int?>("CompanyId");

                    b.Property<string>("CompanyName");

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Rg");

                    b.Property<string>("Uf");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Purveyor");
                });

            modelBuilder.Entity("TestForCompanies.Models.Purveyor", b =>
                {
                    b.HasOne("TestForCompanies.Models.Company", "Company")
                        .WithMany("Purveyors")
                        .HasForeignKey("CompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
